### ISSUE TITLE
Insane divs and performance

### ISSUE THREAD

**Issue by DuskStarGITHUB** [Rupa830904/Project-Portfolio4-Studyalongcultureschool#27]
Try use tags of html, sections, articles, span, and use webp format for yout images, jpg is heavy.

**Comment by Rupa830904** [comment]
Unauthorised.

**Comment by DuskStarGITHUB** [comment]
Well, an ISSUE on a public platform does not make much sense in an authorization, ISSUEs are for requests for improvement and scalability of a repository and its content regardless of whether you know a person or not but i only try to help the projects of people well this issue is closed so have a good day.
